require:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
Metrics/LineLength:
  Max: 100
  Exclude:
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Naming/RescuedExceptionsVariableName:
  PreferredName: 'exception'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

# AllCops:
#   Exclude:
